### ISSUE TITLE
README and Go outdated (references funcs that don't exist)

### ISSUE THREAD

**Issue by kb-sp** [merge-api/merge-go-client#24]
It looks like some changes have been made to the underlying library that aren't reflected in the README, e.g., `mergeclient.ClientWithAuthApiKey()` is mentioned but does not seem to exist, though `mergeclient.WithApiKey()` _does_.

Also, the Go version and `gopkg.in/yaml.v3` are 5-years-old and 5-years-unmaintained, respectively. It would be nice to get a refresh of at least the yaml package to something maintained, e.g., `goccy/go-yaml`. (maybe testify just to keep up)

Thanks!

**Comment by amckinney** [comment]
Fixed in https://github.com/merge-api/merge-go-client/pull/25.

> Also, the Go version and gopkg.in/yaml.v3 are 5-years-old and 5-years-unmaintained, respectively. It would be nice to get a refresh of at least the yaml package to something maintained, e.g., goccy/go-yaml. (maybe testify just to keep up)

For what it's worth, `gopkg.in/yaml.v3` is a transitive dependency only pulled in via [github.com/stretchr/testify](https://github.com/stretchr/testify), which is only used in tests (e.g. [here](https://github.com/merge-api/merge-go-client/blob/4a011226d02135bd004b2311d4810b2221c9f306/client/client_test.go#L8)). The SDK is otherwise built purely on the standard library, so I think the impact here is negligible.

**Comment by hmafzal** [comment]
We've updated the README - thanks for the callout!
